wip

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,9 +4,10 @@
 set -o nounset
 
 PROJECT=randome_engine
-TARGET=${TARGET:-}
-CXX=clang++
-CXXFLAGS=${CXXFLAGS:-}
+BUILD=${BUILD:-}
+CXX="c++"
+CXXFLAGS=${CXXFLAGS:-"-v -std=c++20 -Wall -Wextra --pedantic-errors"}
+
 LIBS=${LIBS:-}           
 
 if [[ -d "/usr/local/opt/gnu-getopt/bin" ]]; then
@@ -42,6 +43,7 @@ function show_usage {
 #
 
 help_option=0
+with_cxx_standard_library=''
 
 parsed_arguments=$(getopt -n $0 -o hv \
     --long help,build:,with-cxx:,with-cxx-standard-library: -- "$@")
@@ -52,14 +54,15 @@ fi
 eval set -- "$parsed_arguments"
 while true; do
     case "$1" in
-        -h | --help     ) help_option=1                 ; shift   ;;
-             --build    ) build="$2"                    ; shift   ;;
-             --with-cxx ) CXX="$2"                      ; shift 2 ;;
-             --with-cxx-standard-library )
-                          with_cxx_standard_library="$2"; shift 2 ;;
-        --) shift; break;;
-        *) echo "Error: Unknown option: $1"
-           show_usage 1;;
+    -h | --help     ) help_option=1                 ; shift   ;;
+         --build    ) BUILD="$2"                    ; shift   ;;
+         --with-cxx ) CXX="$2"                      ; shift 2 ;;
+         --with-cxx-standard-library )
+                      with_cxx_standard_library="$2"; shift 2 ;;
+    -- ) shift
+         break ;;
+    *  ) echo "Error: Unknown option: $1"
+         show_usage 1 ;;
     esac
 done
 
@@ -75,6 +78,19 @@ fi
 if [[ $help_option == 1 ]]; then
    show_usage 0
 fi
+
+case "$BUILD" in
+macos  ) ;;
+ubuntu ) ;;
+*      ) ;;
+esac
+
+case "$with_cxx_standard_library" in
+libstdc++) CXXFLAGS="$CXXFLAGS -stdlib=libstdc++" ;;
+libc++   ) CXXFLAGS="$CXXFLAGS -stdlib=libc++" ;;
+* )        echo "unknown C++ standard library: $with_cxx_standard_library"
+           exit 1 ;;
+esac
 
 for f in Makefile
 do
